export const MATHML_TAG_NAMES: string[] = [
  'math',
  'mrow',
  'mi',
  'mn',
  'mo',
  'mfrac',
  'msup',
  'msub',
  'munder',
  'mover',
  'munderover',
  'msqrt',
  'mroot',
  'mtext',
  'mspace',
  'menclose',
  'mpadded',
  'mphantom',
  'mtable',
  'mtr',
  'mtd',
  'mlabeledtr',
  'maligngroup',
  'malignmark',
  'mstyle',
  'merror',
  'maction',
  'semantics',
  'annotation',
  'annotation-xml',
] as const;

// MathML attribute configuration
export const MATHML_ATTRIBUTES: Record<string, string[]> = {
  math: ['display', 'class', 'style', 'xmlns'],
  mrow: ['class', 'style'],
  mi: ['class', 'style', 'mathvariant'],
  mn: ['class', 'style'],
  mo: [
    'class',
    'style',
    'fence',
    'separator',
    'stretchy',
    'symmetric',
    'largeop',
    'movablelimits',
    'accent',
    'lspace',
    'rspace',
    'form',
  ],
  mfrac: ['class', 'style', 'linethickness', 'numalign', 'denomalign', 'bevelled'],
  msup: ['class', 'style', 'superscriptshift'],
  msub: ['class', 'style', 'subscriptshift'],
  munder: ['class', 'style', 'accentunder'],
  mover: ['class', 'style', 'accent'],
  munderover: ['class', 'style', 'accent', 'accentunder'],
  msqrt: ['class', 'style'],
  mroot: ['class', 'style'],
  mtext: ['class', 'style', 'mathvariant'],
  mspace: ['class', 'style', 'width', 'height', 'depth'],
  menclose: ['class', 'style', 'notation'],
  mpadded: ['class', 'style', 'width', 'height', 'depth', 'lspace', 'voffset'],
  mphantom: ['class', 'style'],
  mtable: [
    'class',
    'style',
    'align',
    'rowalign',
    'columnalign',
    'groupalign',
    'alignmentscope',
    'columnwidth',
    'width',
    'rowspacing',
    'columnspacing',
    'rowlines',
    'columnlines',
    'frame',
    'framespacing',
    'equalrows',
    'equalcolumns',
    'displaystyle',
    'side',
    'minlabelspacing',
  ],
  mtr: ['class', 'style', 'rowalign', 'columnalign', 'groupalign'],
  mtd: ['class', 'style', 'rowspan', 'columnspan', 'rowalign', 'columnalign', 'groupalign'],
  mlabeledtr: ['class', 'style', 'rowalign', 'columnalign', 'groupalign'],
  maligngroup: ['class', 'style', 'groupalign'],
  malignmark: ['class', 'style', 'edge'],
  mstyle: [
    'class',
    'style',
    'scriptlevel',
    'displaystyle',
    'scriptsizemultiplier',
    'scriptminsize',
    'infixlinebreakstyle',
    'decimalpoint',
    'mathvariant',
    'mathsize',
    'mathcolor',
    'mathbackground',
  ],
  merror: ['class', 'style'],
  maction: ['class', 'style', 'actiontype', 'selection'],
  semantics: ['class', 'style'],
  annotation: ['class', 'style', 'encoding'],
  'annotation-xml': ['class', 'style', 'encoding'],
};
